# Supervised Learning: Classification

## Pre-processing

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('../res/heart_trt.csv', sep=';', encoding='utf-8')

### Transforming nominal categorical variables into ordinal categorical variables

In [5]:
df2 = pd.DataFrame.copy(df)

In [6]:
df2.Sex.replace({'M':0, 'F':1}, inplace=True)
df2.ChestPainType.replace({'TA':0, 'ATA':1, 'NAP':2, 'ASY':3}, inplace=True)
df2.RestingECG.replace({'Normal':0, 'ST': 1, 'LVH': 2}, inplace=True)
df2.ExerciseAngina.replace({'N':0, 'Y':1}, inplace=True)
df2.ST_Slope.replace({'Up':0, 'Flat': 1, 'Down':2}, inplace=True) 

C:\Users\Pedro\AppData\Local\Temp\ipykernel_12196\2580376.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2.Sex.replace({'M':0, 'F':1}, inplace=True)
C:\Users\Pedro\AppData\Local\Temp\ipykernel_12196\2580376.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2.Sex.replace({'M':0, 'F':1}, in

In [5]:
df2.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    0              1        140        289.0          0           0   
1   49    1              2        160        180.0          0           0   
2   37    0              1        130        283.0          0           1   
3   48    1              3        138        214.0          0           0   
4   54    0              2        150        195.0          0           0   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         0             0  
1    156               0      1.0         1             1  
2     98               0      0.0         0             0  
3    108               1      1.5         1             1  
4    122               0      0.0         0             0

### Forecasters and target

In [7]:
forecasters = df2.iloc[:, 0:11].values
target = df2.iloc[:, 11].values

### Feature scaling analysis

In [7]:
df2.describe()

Age         Sex  ChestPainType   RestingBP  Cholesterol  \
count  917.000000  917.000000     917.000000  917.000000   917.000000   
mean    53.509269    0.210469       2.251908  132.540894   244.635389   
std      9.437636    0.407864       0.931502   17.999749    53.347125   
min     28.000000    0.000000       0.000000   80.000000    85.000000   
25%     47.000000    0.000000       2.000000  120.000000   214.000000   
50%     54.000000    0.000000       3.000000  130.000000   244.635389   
75%     60.000000    0.000000       3.000000  140.000000   267.000000   
max     77.000000    1.000000       3.000000  200.000000   603.000000   

        FastingBS  RestingECG       MaxHR  ExerciseAngina     Oldpeak  \
count  917.000000  917.000000  917.000000      917.000000  917.000000   
mean     0.233370    0.604144  136.789531        0.404580    0.886696   
std      0.423206    0.806161   25.467129        0.491078    1.066960   
min      0.000000    0.000000   60.000000        0.000000   -2.600000   
25%      0.000000    0.000000  120.000000        0.000000    0.000000   
50%      0.000000    0.000000  138.000000        0.000000    0.600000   
75%      0.000000    1.000000  156.000000        1.000000    1.500000   
max      1.000000    2.000000  202.000000        1.000000    6.200000   

        ST_Slope  HeartDisease  
count  917.00000    917.000000  
mean     0.63795      0.552890  
std      0.60727      0.497466  
min      0.00000      0.000000  
25%      0.00000      0.000000  
50%      1.00000      1.000000  
75%      1.00000      1.000000  
max      2.00000      1.000000

* Standardization (Uses mean and std deviation as references)
* Normalization (Uses min and max as references) 
In this case, I will use standardization.

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
forecasters_scaled = StandardScaler().fit_transform(forecasters)

In [10]:
forecasters_df = pd.DataFrame(forecasters_scaled)
forecasters_df.describe()

0             1             2             3             4   \
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02   
mean   1.859654e-16  7.748558e-18  1.046055e-16  7.767929e-16 -1.869340e-16   
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00   
min   -2.704405e+00 -5.163086e-01 -2.418822e+00 -2.920572e+00 -2.994023e+00   
25%   -6.900904e-01 -5.163086e-01 -2.705801e-01 -6.971063e-01 -5.745784e-01   
50%    5.202558e-02 -5.163086e-01  8.035410e-01 -1.412398e-01  0.000000e+00   
75%    6.881250e-01 -5.163086e-01  8.035410e-01  4.146267e-01  4.194568e-01   
max    2.490407e+00  1.936826e+00  8.035410e-01  3.749826e+00  6.721265e+00   

                 5           6             7             8             9   \
count  9.170000e+02  917.000000  9.170000e+02  9.170000e+02  9.170000e+02   
mean   4.649135e-17    0.000000 -5.114048e-16 -1.046055e-16  7.748558e-17   
std    1.000546e+00    1.000546  1.000546e+00  1.000546e+00  1.000546e+00   
min   -5.517333e-01   -0.749818 -3.016886e+00 -8.243101e-01 -3.269662e+00   
25%   -5.517333e-01   -0.749818 -6.596226e-01 -8.243101e-01 -8.315022e-01   
50%   -5.517333e-01   -0.749818  4.755658e-02 -8.243101e-01 -2.688500e-01   
75%   -5.517333e-01    0.491306  7.547357e-01  1.213136e+00  5.751284e-01   
max    1.812470e+00    1.732430  2.561971e+00  1.213136e+00  4.982571e+00   

                 10  
count  9.170000e+02  
mean  -3.874279e-17  
std    1.000546e+00  
min   -1.051095e+00  
25%   -1.051095e+00  
50%    5.965186e-01  
75%    5.965186e-01  
max    2.244132e+00

### Creating Dummy Variables

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

In [12]:
forecasters2 = df.iloc[:, 0:11].values
forecasters2[:,1] = LabelEncoder().fit_transform(forecasters[:,1])

In [13]:
forecasters2[:,2] = LabelEncoder().fit_transform(forecasters[:,2])
forecasters2[:,6] = LabelEncoder().fit_transform(forecasters[:,6])
forecasters2[:,8] = LabelEncoder().fit_transform(forecasters[:,8])
forecasters2[:,10] = LabelEncoder().fit_transform(forecasters[:,10])

In [14]:
forecasters3 = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,2,6,8,10])], remainder='passthrough').fit_transform(forecasters2)

In [15]:
forecasters3df = pd.DataFrame(forecasters3)
forecasters3df.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13  14  \
0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  40   
1  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  49   
2  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  37   
3  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  48   
4  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  54   

    15     16 17   18   19  
0  140  289.0  0  172  0.0  
1  160  180.0  0  156  1.0  
2  130  283.0  0   98  0.0  
3  138  214.0  0  108  1.5  
4  150  195.0  0  122  0.0

### Scaling the features

In [16]:
forecasters3_esc = StandardScaler().fit_transform(forecasters3)
forecasters3df = pd.DataFrame(forecasters3_esc)
forecasters3df.head()

0         1        2         3         4         5         6   \
0  0.516309 -0.516309 -0.22981  2.073784 -0.531524 -1.085425  0.815013   
1 -1.936826  1.936826 -0.22981 -0.482210  1.881384 -1.085425  0.815013   
2  0.516309 -0.516309 -0.22981  2.073784 -0.531524 -1.085425 -1.226974   
3 -1.936826  1.936826 -0.22981 -0.482210 -0.531524  0.921298  0.815013   
4  0.516309 -0.516309 -0.22981 -0.482210  1.881384 -1.085425  0.815013   

         7         8         9         10        11        12        13  \
0 -0.490781 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   
1 -0.490781 -0.507826  0.824310 -0.824310 -0.869888  0.998910 -0.271607   
2  2.037569 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   
3 -0.490781 -0.507826 -1.213136  1.213136 -0.869888  0.998910 -0.271607   
4 -0.490781 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   

         14        15        16        17        18        19  
0 -1.432206  0.414627  0.832075 -0.551733  1.383339 -0.831502  
1 -0.478057  1.526360 -1.212261 -0.551733  0.754736  0.106251  
2 -1.750256 -0.141240  0.719543 -0.551733 -1.523953 -0.831502  
3 -0.584074  0.303453 -0.574578 -0.551733 -1.131075  0.575128  
4  0.052026  0.970493 -0.930931 -0.551733 -0.581047 -0.831502

In [17]:
forecasters3df.describe()

0             1             2             3             4   \
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02   
mean  -1.472226e-16  1.084798e-16  6.973702e-17 -3.874279e-17  3.874279e-17   
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00   
min   -1.936826e+00 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
25%    5.163086e-01 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
50%    5.163086e-01 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
75%    5.163086e-01 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
max    5.163086e-01  1.936826e+00  4.351412e+00  2.073784e+00  1.881384e+00   

                 5             6             7           8             9   \
count  9.170000e+02  9.170000e+02  9.170000e+02  917.000000  9.170000e+02   
mean   1.937139e-17 -9.298269e-17  1.549712e-17    0.000000 -4.261707e-17   
std    1.000546e+00  1.000546e+00  1.000546e+00    1.000546  1.000546e+00   
min   -1.085425e+00 -1.226974e+00 -4.907810e-01   -0.507826 -1.213136e+00   
25%   -1.085425e+00 -1.226974e+00 -4.907810e-01   -0.507826 -1.213136e+00   
50%    9.212982e-01  8.150134e-01 -4.907810e-01   -0.507826  8.243101e-01   
75%    9.212982e-01  8.150134e-01 -4.907810e-01   -0.507826  8.243101e-01   
max    9.212982e-01  8.150134e-01  2.037569e+00    1.969177  8.243101e-01   

                 10            11          12            13            14  \
count  9.170000e+02  9.170000e+02  917.000000  9.170000e+02  9.170000e+02   
mean   4.261707e-17 -3.874279e-17    0.000000  8.523413e-17  1.859654e-16   
std    1.000546e+00  1.000546e+00    1.000546  1.000546e+00  1.000546e+00   
min   -8.243101e-01 -8.698879e-01   -1.001091 -2.716072e-01 -2.704405e+00   
25%   -8.243101e-01 -8.698879e-01   -1.001091 -2.716072e-01 -6.900904e-01   
50%   -8.243101e-01 -8.698879e-01    0.998910 -2.716072e-01  5.202558e-02   
75%    1.213136e+00  1.149573e+00    0.998910 -2.716072e-01  6.881250e-01   
max    1.213136e+00  1.149573e+00    0.998910  3.681787e+00  2.490407e+00   

                 15            16            17            18            19  
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  
mean   7.884157e-16  3.014189e-15 -1.549712e-17 -5.114048e-16 -1.859654e-16  
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  
min   -2.920572e+00 -2.994023e+00 -5.517333e-01 -3.016886e+00 -3.269662e+00  
25%   -6.971063e-01 -5.745784e-01 -5.517333e-01 -6.596226e-01 -8.315022e-01  
50%   -1.412398e-01  3.198360e-15 -5.517333e-01  4.755658e-02 -2.688500e-01  
75%    4.146267e-01  4.194568e-01 -5.517333e-01  7.547357e-01  5.751284e-01  
max    3.749826e+00  6.721265e+00  1.812470e+00  2.561971e+00  4.982571e+00

### Summarizing pre-processing

* target = variable we want to get to (has or has not heart disease)
* forecasters = set of features with categoric variables transformed manually, no scalling
* forecasters_scaled = set of features with categoric variables transformed manually, scaled.
* forecasters2 = set of features with categoric variables transformed by labelencoder.
* forecasters3 = set of features with categoric variables transformed by labelencoder and onehotencoder
* forecasters3_esc = set of features transformed by labelencoder and onehot encoder, scaled.

### Separating Training Database from Testing Database

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(forecasters3_esc, target, test_size=0.3, random_state=0)

### Support Vector Machine (SVM)

In [18]:
from sklearn.svm import SVC

In [140]:
svm = SVC(kernel='rbf', C=2, random_state=1)
svm.fit(x_train, y_train)

SVC(C=2, random_state=1)

In [141]:
predictions_svm = svm.predict(x_test)
predictions_svm

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [108]:
y_test

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [24]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [142]:
print("Accuracy: %.2f%%" % (accuracy_score(y_test, predictions_svm) * 100))

Accuracy: 86.23%


In [143]:
confusion_matrix(y_test, predictions_svm)

array([[ 99,  22],
       [ 16, 139]])

In [144]:
print(classification_report(y_test, predictions_svm))

              precision    recall  f1-score   support

           0       0.86      0.82      0.84       121
           1       0.86      0.90      0.88       155

    accuracy                           0.86       276
   macro avg       0.86      0.86      0.86       276
weighted avg       0.86      0.86      0.86       276



#### Analyzing training data

In [145]:
predictions_training = svm.predict(x_train)
predictions_training

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,

In [146]:
accuracy_score(y_train, predictions_training)

0.9282371294851794

In [147]:
confusion_matrix(y_train, predictions_training)

array([[257,  32],
       [ 14, 338]])

#### Cross-Validation

In [148]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [149]:
kfold = KFold(n_splits=30, random_state=5, shuffle=True)

In [162]:
model = SVC(kernel='rbf', C=2, random_state=1)
result = cross_val_score(model, forecasters3_esc, target, cv=kfold)

print("Avg. Accuracy: %.2f%%" % (result.mean() * 100))

Avg. Accuracy: 85.72%


### K-Nearest Neighbors (KNN)

In [163]:
from sklearn.neighbors import KNeighborsClassifier

In [230]:
knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [233]:
predictions_knn = knn.predict(x_test)
 

In [231]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [234]:
print("Accuracy: %.2f%%" % (accuracy_score(y_test, predictions_knn) * 100))

Accuracy: 84.78%


In [190]:
confusion_matrix(y_test, predictions_knn)

array([[ 98,  23],
       [ 19, 136]])

In [235]:
print(classification_report(y_test, predictions_knn))

              precision    recall  f1-score   support

           0       0.84      0.81      0.82       121
           1       0.86      0.88      0.87       155

    accuracy                           0.85       276
   macro avg       0.85      0.84      0.84       276
weighted avg       0.85      0.85      0.85       276



#### Analyzing training data

In [236]:
predictions_training = knn.predict(x_train)

In [237]:
accuracy_score(y_train, predictions_training)

0.8939157566302652

In [238]:
confusion_matrix(y_train, predictions_training)

array([[249,  40],
       [ 28, 324]])

#### Cross-Validation

In [239]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [240]:
kfold = KFold(n_splits=30, random_state=5, shuffle=True)

In [241]:
model = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
result = cross_val_score(model, forecasters3_esc, target, cv=kfold)

print("Avg. Accuracy: %.2f%%" % (result.mean() * 100))

Avg. Accuracy: 85.83%


### Decision Tree

In [242]:
from sklearn.tree import DecisionTreeClassifier

In [256]:
tree = DecisionTreeClassifier(criterion='entropy', random_state=0)
tree.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [257]:
predictions_tree = tree.predict(x_test)

In [245]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [258]:
print("Accuracy: %.2f%%" % (accuracy_score(y_test, predictions_tree) * 100))

Accuracy: 81.16%


#### Cross-Validation

In [259]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [292]:
kfold = KFold(n_splits=30, random_state=5, shuffle=True)
model = DecisionTreeClassifier(criterion='entropy', random_state=0, max_depth=4)
result = cross_val_score(model, forecasters, target, cv=kfold)

print("Avg. Accuracy: %.2f%%" % (result.mean() * 100))

Avg. Accuracy: 83.87%


### Artificial Neural Network

In [230]:
x_train, x_test, y_train, y_test = train_test_split(forecasters3, target, test_size=0.3, random_state=0)

In [21]:
from sklearn.neural_network import MLPClassifier

In [231]:
network = MLPClassifier(hidden_layer_sizes=(7,6,7), activation='logistic', solver='adam', max_iter=800, tol=0.00001, random_state=12, verbose=True)

In [232]:
network.fit(x_train, y_train)

Iteration 1, loss = 0.68866635
Iteration 2, loss = 0.68838710
Iteration 3, loss = 0.68819766
Iteration 4, loss = 0.68805988
Iteration 5, loss = 0.68787965
Iteration 6, loss = 0.68771733
Iteration 7, loss = 0.68759059
Iteration 8, loss = 0.68758397
Iteration 9, loss = 0.68753894
Iteration 10, loss = 0.68744463
Iteration 11, loss = 0.68739337
Iteration 12, loss = 0.68734073
Iteration 13, loss = 0.68726902
Iteration 14, loss = 0.68718456
Iteration 15, loss = 0.68713033
Iteration 16, loss = 0.68713482
Iteration 17, loss = 0.68699769
Iteration 18, loss = 0.68690603
Iteration 19, loss = 0.68684608
Iteration 20, loss = 0.68677213
Iteration 21, loss = 0.68670020
Iteration 22, loss = 0.68662146
Iteration 23, loss = 0.68661411
Iteration 24, loss = 0.68649969
Iteration 25, loss = 0.68634150
Iteration 26, loss = 0.68621734
Iteration 27, loss = 0.68601867
Iteration 28, loss = 0.68575337
Iteration 29, loss = 0.68546999
Iteration 30, loss = 0.68526829
Iteration 31, loss = 0.68509807
Iteration 32, los

MLPClassifier(activation='logistic', hidden_layer_sizes=(7, 6, 7), max_iter=800,
              random_state=12, tol=1e-05, verbose=True)

In [233]:
predictions_network = network.predict(x_test)

In [234]:
predictions_network

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [235]:
print("Accuracy: %.2f%%" % (accuracy_score(y_test, predictions_network) * 100))

Accuracy: 87.68%


#### Cross-Validation

In [236]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [237]:
kfold = KFold(n_splits=30, random_state=5, shuffle=True)

In [239]:
model = MLPClassifier(hidden_layer_sizes=(7,6,7), activation='logistic', solver='adam', max_iter=800, tol=0.00001, random_state=12, verbose=True)

result = cross_val_score(model, forecasters3, target, cv=kfold)

Iteration 1, loss = 0.68785550
Iteration 2, loss = 0.68757579
Iteration 3, loss = 0.68743250
Iteration 4, loss = 0.68729170
Iteration 5, loss = 0.68708247
Iteration 6, loss = 0.68698052
Iteration 7, loss = 0.68692590
Iteration 8, loss = 0.68679440
Iteration 9, loss = 0.68673707
Iteration 10, loss = 0.68662508
Iteration 11, loss = 0.68652701
Iteration 12, loss = 0.68641159
Iteration 13, loss = 0.68627594
Iteration 14, loss = 0.68611280
Iteration 15, loss = 0.68595799
Iteration 16, loss = 0.68578782
Iteration 17, loss = 0.68561365
Iteration 18, loss = 0.68543252
Iteration 19, loss = 0.68521255
Iteration 20, loss = 0.68501484
Iteration 21, loss = 0.68476067
Iteration 22, loss = 0.68437923
Iteration 23, loss = 0.68390343
Iteration 24, loss = 0.68345292
Iteration 25, loss = 0.68316283
Iteration 26, loss = 0.68285979
Iteration 27, loss = 0.68239893
Iteration 28, loss = 0.68206110
Iteration 29, loss = 0.68154575
Iteration 30, loss = 0.68117786
Iteration 31, loss = 0.68066620
Iteration 32, los

In [240]:
print("Avg. Accuracy: %.2f%%" % (result.mean() * 100))

Avg. Accuracy: 86.91%
